rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx-19mode

env:
  - RAILS_VERSION="~> 3.1.0"
  - RAILS_VERSION="~> 3.2.0"
  - RAILS_VERSION="~> 4.0.0"
  - RAILS_VERSION="~> 4.1.0"
  - RAILS_VERSION="~> 4.2.0"
  - RAILS_VERSION="~> 5.0.0"
  # Do we need to test each rspec version with each rails?
  # Since rspec has no direct relation to rails (except through rspec-rails,
  # which isn't considered here), I'm assuming no.
  - RAILS_VERSION="none"     RSPEC_VERSION="~> 2.0"
  - RAILS_VERSION="none"     RSPEC_VERSION="~> 3.0"
  # don't use rails, but define a module called Rails. This happens if you
  # pull in ActiveRecord and then require AR's generators.
  - RAILS_VERSION="none"     DEFINE_RAILS_MODULE=1

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
  exclude:
    - rvm: 2.3.0
      env: RAILS_VERSION="~> 3.1.0"
    - rvm: 2.3.0
      env: RAILS_VERSION="~> 3.2.0"
    - rvm: 2.0.0
      env: RAILS_VERSION="~> 5.0.0"
    - rvm: 2.1.8
      env: RAILS_VERSION="~> 5.0.0"
